# Generated by Django 5.1.7 on 2025-03-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='MobileNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='signupdetails',
            name='Customer_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
